test: SJ-2115 Creates allure report for Chromatic / storybook test results (#629)
* chore: SJ-2115 generates junit report in chromatic

* test: SJ-2115 creates new allure report for chromatic test results

* chore: SJ-2115 dummy change to trigger chromatic workflow

diff --git a/.github/workflows/chromatic.yml b/.github/workflows/chromatic.yml
--- a/.github/workflows/chromatic.yml
+++ b/.github/workflows/chromatic.yml
@@ -50,3 +50,35 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           # 👇 Chromatic projectToken, refer to the manage page to obtain it.
           projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
+          junitReport: true
+      - name: Upload JUnit test results
+        uses: actions/upload-artifact@v4
+        if: success() || failure()
+        with:
+          if-no-files-found: warn
+          name: chromatic-test-results
+          path: '**/*/chromatic-build-*.xml'
+      - name: Copy junit report to allure-results
+        run: |
+          mkdir -p ./output/allure-results
+          # Replace <variable> with your actual variable
+          FILE=$(find . -name "chromatic-build-*.xml")
+          if [ -n "$FILE" ]; then
+            cp "$FILE" ./output/allure-results
+          else
+            echo "File not found"
+          fi
+      - name: Publish allure results
+        uses: actions/upload-artifact@v4
+        if: success() || failure()
+        with:
+          if-no-files-found: warn
+          name: allure-storybook-tests
+          path: "**/output"
+
+  AllureReportPustToS3:
+    uses: linz/github-action-shared-library/.github/workflows/publish-allure-report-to-s3-workflow.yml@master
+    needs: [chromatic-deployment]
+    if: ${{ !cancelled() }}
+    with:
+      allureReportS3Subfolder: "chromatic"
